CREATE TABLE CONTAINERSIZE (
       CONTAINERSIZEID BIGINT(20) NOT NULL AUTO_INCREMENT
     , SIZE VARCHAR(20) NOT NULL
     , DESCRIPTION VARCHAR(100)
     , PRIMARY KEY(CONTAINERSIZEID)
)TYPE=INNODB;

CREATE TABLE CONTAINERTYPE (
       CONTAINERTYPEID BIGINT(20) NOT NULL AUTO_INCREMENT
     , TYPE VARCHAR(20) NOT NULL
     , DESCRIPTION VARCHAR(100)
     , PRIMARY KEY(CONTAINERTYPEID)
)TYPE=INNODB;

CREATE TABLE COUNTRY (
       COUNTRYID BIGINT(20) NOT NULL AUTO_INCREMENT
     , CODE VARCHAR(5) NOT NULL
     , NAME VARCHAR(100) NOT NULL
     , PRIMARY KEY(COUNTRYID)
)TYPE=INNODB;

CREATE TABLE LOCATION (
       LOCATIONID BIGINT(20) NOT NULL AUTO_INCREMENT
     , CODE TEXT
     , LOCATION TEXT
     , ISPORT CHAR(1)
     , PRIMARY KEY(LOCATIONID)
)TYPE=INNODB;

CREATE TABLE OFFICE (
       OFFICEID BIGINT(20) NOT NULL AUTO_INCREMENT
     , OFFICE TEXT
     , DESCRIPTION TEXT
     , CODE TEXT
     , PRIMARY KEY(OFFICEID)
)TYPE=INNODB;

CREATE TABLE PACK (
       PACKID BIGINT(20) NOT NULL AUTO_INCREMENT
     , TYPE TEXT
     , DESCRIPTION TEXT
     , PRIMARY KEY(PACKID)
)TYPE=INNODB;

CREATE TABLE COMMODITY (
       COMMODITYID BIGINT(20) NOT NULL AUTO_INCREMENT
     , CODE TEXT
     , NAME TEXT
     , DESCRIPTION TEXT
     , PRIMARY KEY(COMMODITYID)
)TYPE=INNODB;

CREATE TABLE VESSEL (
       VESSELID BIGINT(20) NOT NULL AUTO_INCREMENT
     , VESSELCODE TEXT
     , VESSELNAME TEXT
     , FLAG BIGINT(20)
     , STATUS BIGINT(20)
     , COMPANY TEXT
     , PORT BIGINT(20)
     , PRIMARY KEY(VESSELID)
)TYPE=INNODB;

CREATE TABLE VOYAGE (
       VOYAGEID BIGINT(20) NOT NULL AUTO_INCREMENT
     , VOYAGE TEXT
     , EXPORT BIGINT(20)
     , VESSELID BIGINT(20)
     , OFFICEID BIGINT(20)
     , STATUS BIGINT(20)
     , FIRSTLEAVEDPORT BIGINT(20)
     , LASTLEAVEDPORT BIGINT(20)
     , ARRIVALDATE DATE
     , DEPARTUREDATE DATE
     , NAMEOFCAPTAIN TEXT
     , PRIMARY KEY(VOYAGEID)
)TYPE=INNODB;

CREATE TABLE BL (
       BLID BIGINT(20) NOT NULL AUTO_INCREMENT
     , VOYAGEID BIGINT(20)
     , BLNO TEXT
     , COMPANYNAME TEXT
     , STATUS BIGINT(20)
     , REPORTTYPE BIGINT(20)
     , PLACEOFORIGIN BIGINT(20)
     , PLACEOFRECEIPT BIGINT(20)
     , PORTOFLOADING BIGINT(20)
     , PORTOFDISCHARGE BIGINT(20)
     , FINALDISCHARGEPLACE BIGINT(20)
     , FINALDESTINATION BIGINT(20)
     , DESCRIPTION TEXT
     , DESCRIPTION2 TEXT
     , SHIPPER TEXT
     , CONSIGNEE TEXT
     , NOTIFY TEXT
     , NOTIFY2 TEXT
     , ISSUEPLACE BIGINT(20) DEFAULT 0
     , ISSUEDATE DATE
     , PRIMARY KEY(BLID)
)TYPE=INNODB;

CREATE TABLE CONTAINER (
       CONTAINERID BIGINT(20) NOT NULL AUTO_INCREMENT
     , CONTAINERNO TEXT
     , BLID BIGINT(20)
     , CONTAINERTYPE BIGINT(20)
     , SEALNO TEXT
     , OTHERSEALNO TEXT
     , CONTAINERSIZE BIGINT(20)
     , TARAWEIGHT DOUBLE
     , STATUS BIGINT(20)
     , RELCOM BIGINT(20)
     , PRIMARY KEY(CONTAINERID)
)TYPE=INNODB;

CREATE TABLE CARGO (
       CARGOID BIGINT(20) NOT NULL AUTO_INCREMENT
     , CONTAINERID BIGINT(20) NOT NULL
     , COMMODITYID BIGINT(20) NOT NULL
     , CARGOTYPE TEXT
     , PACKID BIGINT(20)
     , IMCO TEXT
     , UNNO TEXT
     , NETWEIGHT DOUBLE DEFAULT 0
     , PACKTOTAL DOUBLE
     , PRIMARY KEY(CARGOID)
)TYPE=INNODB;

ALTER TABLE VESSEL
  ADD CONSTRAINT FK_VESSEL_COUNTRY
      FOREIGN KEY (FLAG)
      REFERENCES COUNTRY (COUNTRYID)
   ON DELETE NO ACTION
   ON UPDATE NO ACTION;

ALTER TABLE VESSEL
  ADD CONSTRAINT FK_VESSEL_LOCATION
      FOREIGN KEY (PORT)
      REFERENCES LOCATION (LOCATIONID)
   ON DELETE NO ACTION
   ON UPDATE NO ACTION;

ALTER TABLE VOYAGE
  ADD CONSTRAINT FK_VOYAGE_1
      FOREIGN KEY (VESSELID)
      REFERENCES VESSEL (VESSELID)
   ON DELETE NO ACTION
   ON UPDATE NO ACTION;

ALTER TABLE VOYAGE
  ADD CONSTRAINT FK_VOYAGE_LOCATION_1
      FOREIGN KEY (FIRSTLEAVEDPORT)
      REFERENCES LOCATION (LOCATIONID)
   ON DELETE NO ACTION
   ON UPDATE NO ACTION;

ALTER TABLE VOYAGE
  ADD CONSTRAINT FK_VOYAGE_LOCATION_2
      FOREIGN KEY (LASTLEAVEDPORT)
      REFERENCES LOCATION (LOCATIONID)
   ON DELETE NO ACTION
   ON UPDATE NO ACTION;

ALTER TABLE VOYAGE
  ADD CONSTRAINT FK_VOYAGE_OFFICE
      FOREIGN KEY (OFFICEID)
      REFERENCES OFFICE (OFFICEID)
   ON DELETE NO ACTION
   ON UPDATE NO ACTION;

ALTER TABLE BL
  ADD CONSTRAINT FK_BL_1
      FOREIGN KEY (VOYAGEID)
      REFERENCES VOYAGE (VOYAGEID)
   ON DELETE NO ACTION
   ON UPDATE NO ACTION;

ALTER TABLE BL
  ADD CONSTRAINT FK_BL_LOCATION_1
      FOREIGN KEY (PLACEOFORIGIN)
      REFERENCES LOCATION (LOCATIONID)
   ON DELETE NO ACTION
   ON UPDATE NO ACTION;

ALTER TABLE BL
  ADD CONSTRAINT FK_BL_LOCATION_2
      FOREIGN KEY (PLACEOFRECEIPT)
      REFERENCES LOCATION (LOCATIONID)
   ON DELETE NO ACTION
   ON UPDATE NO ACTION;

ALTER TABLE BL
  ADD CONSTRAINT FK_BL_LOCATION_3
      FOREIGN KEY (PORTOFLOADING)
      REFERENCES LOCATION (LOCATIONID)
   ON DELETE NO ACTION
   ON UPDATE NO ACTION;

ALTER TABLE BL
  ADD CONSTRAINT FK_BL_LOCATION_4
      FOREIGN KEY (PORTOFDISCHARGE)
      REFERENCES LOCATION (LOCATIONID)
   ON DELETE NO ACTION
   ON UPDATE NO ACTION;

ALTER TABLE BL
  ADD CONSTRAINT FK_BL_LOCATION_5
      FOREIGN KEY (FINALDISCHARGEPLACE)
      REFERENCES LOCATION (LOCATIONID)
   ON DELETE NO ACTION
   ON UPDATE NO ACTION;

ALTER TABLE BL
  ADD CONSTRAINT FK_BL_LOCATION_6
      FOREIGN KEY (FINALDESTINATION)
      REFERENCES LOCATION (LOCATIONID)
   ON DELETE NO ACTION
   ON UPDATE NO ACTION;

ALTER TABLE CONTAINER
  ADD CONSTRAINT FK_CONTAINER_2
      FOREIGN KEY (BLID)
      REFERENCES BL (BLID)
   ON DELETE NO ACTION
   ON UPDATE NO ACTION;

ALTER TABLE CONTAINER
  ADD CONSTRAINT FK_CONTAINER_3
      FOREIGN KEY (CONTAINERSIZE)
      REFERENCES CONTAINERSIZE (CONTAINERSIZEID)
   ON DELETE NO ACTION
   ON UPDATE NO ACTION;

ALTER TABLE CONTAINER
  ADD CONSTRAINT FK_CONTAINER_CONTAINERTYPE
      FOREIGN KEY (CONTAINERTYPE)
      REFERENCES CONTAINERTYPE (CONTAINERTYPEID)
   ON DELETE NO ACTION
   ON UPDATE NO ACTION;

ALTER TABLE CARGO
  ADD CONSTRAINT FK_CARGO_2
      FOREIGN KEY (PACKID)
      REFERENCES PACK (PACKID)
   ON DELETE NO ACTION
   ON UPDATE NO ACTION;

ALTER TABLE CARGO
  ADD CONSTRAINT FK_CARGO_3
      FOREIGN KEY (CONTAINERID)
      REFERENCES CONTAINER (CONTAINERID)
   ON DELETE NO ACTION
   ON UPDATE NO ACTION;

ALTER TABLE CARGO
  ADD CONSTRAINT FK_CARGO_4
      FOREIGN KEY (COMMODITYID)
      REFERENCES COMMODITY (COMMODITYID)
   ON DELETE NO ACTION
   ON UPDATE NO ACTION;
   
--vwcontainerlist
CREATE VIEW VWCONTAINERLIST AS
	SELECT	CONTAINER.BLID AS BLID,CONTAINER.CONTAINERNO AS CONTAINERNO,CONTAINERTYPE.TYPE AS TYPE,
			CONTAINERSIZE.SIZE AS SIZE,CONTAINER.SEALNO AS SEALNO 
	FROM ((CONTAINER LEFT JOIN CONTAINERTYPE ON((CONTAINER.CONTAINERTYPE = CONTAINERTYPE.CONTAINERTYPEID))) 
			LEFT JOIN CONTAINERSIZE ON((CONTAINER.CONTAINERSIZE = CONTAINERSIZE.CONTAINERSIZEID)));
--vwcargodetails
CREATE VIEW	VWCARGODETAILS AS SELECT CONTAINER.BLID AS BLID,SUM(CARGO.PACKTOTAL) AS PACKTOTAL,
			COUNT(CONTAINER.CONTAINERNO) AS CONTAINERCOUNT,CONTAINERSIZE.SIZE AS SIZE,
			PACK.TYPE AS TYPE 
	FROM (CONTAINERSIZE LEFT JOIN (CONTAINER LEFT JOIN (CARGO LEFT JOIN PACK ON((CARGO.PACKID = PACK.PACKID))) 
					ON((CONTAINER.CONTAINERID = CARGO.CONTAINERID))) 
					ON((CONTAINER.CONTAINERSIZE = CONTAINERSIZE.CONTAINERSIZEID))) 
		GROUP BY CONTAINER.CONTAINERSIZE;
--vwboflading
CREATE VIEW VWBOFLADING AS
	SELECT	BL.BLID AS BLID,BL.BLNO AS BLNO,BL.SHIPPER AS SHIPPER,BL.CONSIGNEE AS CONSIGNEE,
			BL.NOTIFY AS NOTIFY,BL.NOTIFY2 AS NOTIFY2,BL.DESCRIPTION AS DESCRIPTION,
			BL.ISSUEDATE AS ISSUEDATE,VOYAGE.VOYAGEID AS VOYAGEID,VOYAGE.VOYAGE AS VOYAGE,
			VESSEL.VESSELCODE AS VESSELCODE,VESSEL.VESSELNAME AS VESSELNAME,
			LOCATION.LOCATION AS PLACEOFRECEIPT,LOCATION_1.LOCATION AS PORTOFDISCHARGE,
			LOCATION_2.LOCATION AS PORTOFLOADING,LOCATION_3.LOCATION AS FINALDISCHARGEPLACE,
			LOCATION_4.LOCATION AS ISSUEPLACE 
	FROM (((((((BL JOIN VOYAGE ON((BL.VOYAGEID = VOYAGE.VOYAGEID))) 
			JOIN VESSEL ON((VOYAGE.VESSELID = VESSEL.VESSELID))) 
			LEFT JOIN LOCATION LOCATION_2 ON((BL.PORTOFLOADING = LOCATION_2.LOCATIONID))) 
			LEFT JOIN LOCATION LOCATION_3 ON((BL.FINALDISCHARGEPLACE = LOCATION_3.LOCATIONID))) 
			LEFT JOIN LOCATION LOCATION_1 ON((BL.PORTOFDISCHARGE = LOCATION_1.LOCATIONID))) 
			LEFT JOIN LOCATION ON((BL.PORTOFLOADING = LOCATION.LOCATIONID))) 
			LEFT JOIN LOCATION LOCATION_4 ON((BL.ISSUEPLACE = LOCATION_4.LOCATIONID)));